#!/bin/sh
#
# Called by "git commit" with no arguments.  The hook will cause commit to fail if
# any committed file contains  blacklisted text
#
# To enable this hook, rename this file to "pre-commit".

BLACK_LIST="NOCOMMIT|nocommit"

for FILE in $(git diff-index --name-status --cached HEAD -- | cut -c3-) ; do
  # Check if the file contains one of the words in LIST
  if rg "$BLACK_LIST" "$FILE"; then
    echo "$FILE has one of the black-listed words you don't want to commit. Please remove it"
    exit 1
  fi
done

exit 0
